[Issue-4]  Typescript Migration & Improvements (WIP)
Zillacracy-org/ssibrowser.com pull request #7
Opened 2021-05-20 21:36 UTC by Dorian30

## Summary

pending

## Screenshots

pending

## Issue

pending

2021-05-21 00:12 UTC, tralcanx requested changes
Muy bueno!! Thanks a lot @Dorian30

2021-05-21 00:12 UTC, tralcanx commented on src/components/createAccount.js
> +  const [savePassport, setSavePassport] = useState(
this could be in one line :)

2021-05-21 00:12 UTC, tralcanx commented on src/components/Profile/index.tsx
> +  arweave: any;
here we don't need arweave, arconnect and keyfile if using those globally

2021-05-21 00:12 UTC, tralcanx commented on src/components/Profile/index.tsx
> +  arweave: any;
for account we'll define a new data model comprising the DID smart contract's state.

2021-05-21 00:12 UTC, tralcanx commented on src/components/createAccount.js
> +  pscMember,
remove pscMember, arweave, arconnect and keyfile.

2021-05-21 00:12 UTC, tralcanx commented on src/constants/arconnect.ts
> +  ACCESS_ADDRESS = 'ACCESS_ADDRESS',
atm we only check for this permission to be satisfied but should do it for the 4 of them (when setting arconnect).

2021-05-21 00:12 UTC, tralcanx commented on src/constants/ayja.ts
> +export const ayjaPstStateID = "0QhUKXU_M_jiOc7mT6VvdX8RkbHohx8S627oDDPdnBE";
deprecated - remove this whole file.

2021-05-21 00:14 UTC, Dorian30 commented on src/components/ArConnect/styles.module.scss
> +  // @TODO: think of some styles for this
That's a global style ? I'll check it.

2021-05-21 00:14 UTC, Dorian30 commented on src/components/ConnectWallet/index.tsx
> +import arweave from '../../config/airwave';
Oh! You're right, I'll rename it.

2021-05-24 13:29 UTC, Dorian30 commented on src/components/ConnectWallet/index.tsx
> +  // const [save, setSave] = useState("Save keyfile");
I moved this to a custom component `KeyFile`. 

I didn't move it to useAuthentication hooks 'cause even when it is analogous to arConnect they are not the same. So, I thought a component to handle that specific behaviour was more composable.

2021-05-24 13:31 UTC, Dorian30 commented on src/components/Profile/index.tsx
> +  arweave: any;
Yes, I agree with deleting these props since we are already handling those globally. I'll leave account as any until we have the new model.

2021-05-24 16:17 UTC, tralcanx approved these changes
Great! Ready to merge.

2021-05-24 16:18 UTC, merged