SSI Browser - Search bar
Zillacracy-org/ssibrowser.com pull request #8
Opened 2021-05-26 16:46 UTC by Dorian30

## Summary

- Added smart contracts urls and supported domains
- Added user actions for storing authentication keys while the app is running.
- Built search bar and fixed the corresponding animation.

## Screenshots

![Searchbar](https://user-images.githubusercontent.com/36488701/119699429-8be5e200-be28-11eb-96d0-08058016b850.gif)

## Issue

N/A

2021-05-26 17:18 UTC, tralcanx requested changes
Some details left before merging :) Thank you @Dorian30!!

2021-05-26 17:18 UTC, tralcanx commented on src/constants/domains.ts
> +  DOMAINS.DID,
This one got repeated. DOMAINS.TYRON missing?

2021-05-26 17:18 UTC, tralcanx commented on src/constants/tyron.ts
> +  PST = "pst",
Let's also add psti (https://github.com/pungtas/smart-contracts.tyron/blob/main/PST/new-token/PSTi.tyron.scilla), xpsti (https://github.com/pungtas/smart-contracts.tyron/blob/main/PST/wrapped-token/xPSTi.tyron.scilla) and xwallet (https://github.com/pungtas/smart-contracts.tyron/blob/main/DID/DIDdapps/DIDxWallet.tyron.scilla)

2021-05-26 19:54 UTC, tralcanx commented on src/components/SearchBar/index.tsx
> +      switch (domain) {
here we could do isValidDomain(domain); switch(domain)...

2021-05-27 22:35 UTC, tralcanx commented
ya fue, agrego esos detalles yo. todo bien

2021-05-27 22:37 UTC, merged

2021-05-27 22:45 UTC, Dorian30 commented on src/components/SearchBar/index.tsx
> +      switch (domain) {
Saw this is is already merged, still I'll answer the comments for the next PR. I didn't do isValid domain here because we can already solve that with switch statement.

2021-05-27 22:47 UTC, Dorian30 commented on src/constants/domains.ts
> +  DOMAINS.DID,
Yes, the DID needs to be deleted since it is twice and the Tyron one is missing.

2021-05-27 22:57 UTC, tralcanx commented on src/components/SearchBar/index.tsx
> +      switch (domain) {
oh that's right. but then what is isValidDomain for?

2021-05-27 23:05 UTC, Dorian30 commented on src/components/SearchBar/index.tsx
> +      switch (domain) {
For now, it has no purpose unless we need to validate something else but we can delete as of it now 'cause the switch statement already catches every valid domain.

2021-05-27 23:28 UTC, tralcanx commented on src/components/SearchBar/index.tsx
> +      switch (domain) {
I got it deleted already